server {
    listen         80;
    server_name    iot.welinklab.com;
    return         301 https://$server_name$request_uri;
}

server {
    server_name  iot.welinklab.com;
    listen  443 ssl;
    ssl_certificate conf.d/cert/star.welinklab.com.crt;
    ssl_certificate_key conf.d/cert/star.welinklab.com.key;

    location /smart-relay/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        client_max_body_size 64m;
    }

    location / {
        proxy_pass http://127.0.0.1:18083;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header XHttpScheme "$scheme";
    }

    location /live {
        root /var/www/iot.welinklab.com/;
        index index.html;
    }
}
